Add PixelFormats
tomba/pixutils pull request #3
Opened 2024-12-06 20:13 UTC by sylpe

Add Mono and Bayer Pixel Formats.

2024-12-16 06:14 UTC, tomba requested changes

2024-12-16 06:14 UTC, tomba commented on pixutils/formats/pixelformats.py
> +        ( 1, 1 ),
This should be ( 4, 1 )

2024-12-16 06:14 UTC, tomba commented on pixutils/formats/pixelformats.py
> +        ( ( 4, 2 ), ),
( 2, 1 )

2024-12-16 06:14 UTC, tomba commented on pixutils/formats/pixelformats.py
> +        ( 1, 1 ),
( 2, 1 )

2024-12-16 06:14 UTC, tomba commented on pixutils/formats/pixelformats.py
> +        ( ( 6, 4 ), ),
( 3, 2 )

2024-12-16 06:14 UTC, tomba commented on pixutils/formats/pixelformats.py
> +        ( ( 6, 4 ), ),
These should be ( 3, 2 ). Or do you think line widths with odd number of bytes is not ok?

2025-01-02 15:29 UTC, sylpe commented on pixutils/formats/pixelformats.py
> +        ( ( 4, 2 ), ),
Yes agree! ( 2, 1 ) seems better.

To be honest, this PixelFormat class isn't totally clear for me and I mimic SRGGB10 description. (At the beginning I was expecting ( 2, 1 ) for SRGGB10, I suspect that (4, 2) is linked to the 2x2 pattern on one line? )

2025-01-02 15:30 UTC, sylpe commented on pixutils/formats/pixelformats.py
> +        ( 1, 1 ),
Ok, helps me to better understand 'SRGGB10P' definition.

2025-01-02 15:30 UTC, sylpe commented on pixutils/formats/pixelformats.py
> +        ( ( 4, 2 ), ),
Same as above. Ok.

2025-01-02 15:42 UTC, sylpe commented on pixutils/formats/pixelformats.py
> +        ( 1, 1 ),
Well, I was more expecting ( 4, 1 ) ... To be homogenous with Y10P.
But I suspect your answer to be linked with the ( 3, 2 ) below instead of ( 6, 4 )  ?

2025-01-06 11:32 UTC, tomba commented on pixutils/formats/pixelformats.py
> +        ( ( 4, 2 ), ),
The PixelFormat class is still under work. I agree it's not the easiest one to understand, and maybe it doesn't even cover all the cases yes.

I just pushed "test-format.py" script which may help to test and understand formats.

For Y10, `pixel_align = (1, 1)` means that the format is made from individual pixels, no "macro pixels" or "pixel groups". `planes = ( ( 2, 1 ), )` means that there's a single plane, and one block of pixels takes 2 bytes, and contains 1 pixel (i.e. one pixel takes 2 bytes).

2025-01-06 11:43 UTC, tomba commented on pixutils/formats/pixelformats.py
> +        ( 1, 1 ),
Y10P and Y12P are packed differently.

Y10P has 4 pixels in 5 bytes. Y12P has 2 pixels in 3 bytes. So for Y12P, `( 2, 1 )` says that there are always an even number of pixels in a row, and `( ( 3, 2 ), ),` says that each block is formed from 3 bytes, which contain two pixels. Yes, there's some overlap in those two, but I think `pixel_align` makes things simpler when dealing with multi-plane formats with hsub and vsub.

2025-01-06 12:39 UTC, sylpe commented on pixutils/formats/pixelformats.py
> +        ( 1, 1 ),
Wow, my very bad... For an unknown reason, I was thinking that Y12P was 4 pixels in 6 bytes ...
I double check the spec ... and you're right. Please ignore my previous comment...

2025-01-06 12:56 UTC, sylpe commented
While rebasing, I also pushed another commit please ignore it...

2025-02-16 08:15 UTC, tomba commented
Merged, thanks!

2025-02-16 08:15 UTC, closed without merging